version: '3.6'

services:
  deals_db:
    env_file: .env
    image: mysql:8.0.31-debian
    container_name: deals_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.docker/database:/var/lib/mysql
      - ./.docker/init:/docker-entrypoint-initdb.d
  deals_backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: ../.docker/backendDockerfile
    container_name: deals_backend
    restart: always
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend:rw
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - deals_db
  deals_frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: ../.docker/frontendDockerfile
    container_name: deals_frontend
    restart: always
    volumes:
      - ./frontend:/app/frontend:rw
    ports:
      - "${FRONTEND_PORT}:8000"
  deals_phpmyadmin:
    env_file: .env
    container_name: deals_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITARY=1
      - PMA_CONTROLPORT="${MYSQL_PORT}"
    volumes:
      - ./.docker/sessions
