version: '3.6'

services:
  db:
    container_name: deals_db
    image: mariadb:10.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
  backend:
    container_name: deals_backend
    build: backend
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app/backend
    ports:
      - "81:8000"
    depends_on:
      - db
  frontend:
    container_name: deals_frontend
    build: frontend
    restart: always
    command: npm run start
    volumes:
      - .:/app/frontend
    ports:
      - "82:80"
  phpmyadmin:
    container_name: deals_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "666:80"
    environment:
      - PMA_ARBITARY=1
      - PMA_CONTROLPORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /sessions
